name: custom workflow with dependencies

on:
  workflow_dispatch:  # Trigger manually from the Actions tab

jobs:
  # First Job: Setup Greeting
  setup-greeting:
    runs-on: ubuntu-latest
    env:
      GREETING: "Hello"
      NAME: "Lina"
    steps:
      - name: Display Initial Greeting
        run: echo "${{ env.GREETING }}, ${{ env.NAME }}!"
    
  # Second Job: Use Secret and Greeting
  use-secret:
    runs-on: ubuntu-latest
    needs: setup-greeting  # This job depends on 'setup-greeting' job
    env:
      GREETING: "Hello again"
      NAME: "Lina"
      SECRET_KEY: ${{ secrets.MY_SECRET_KEY }}  # Uses a secret stored in repo settings

    steps:
      - name: Display Greeting with Secret
        run: |
          echo "${{ env.GREETING }}, ${{ env.NAME }}!"
          echo "Using Secret: ${{ env.SECRET_KEY }}"
          echo "Workflow Run ID: ${{ github.run_id }}"
          echo "Triggered by: ${{ github.actor }}"

      - name: Show Environment and GitHub Variables
        run: |
          echo "Custom Greeting: ${{ env.GREETING }} ${{ env.NAME }}"
          echo "Current branch: ${{ github.ref_name }}"
          echo "Repository: ${{ github.repository }}"
